# Generated by Django 4.2.7 on 2023-11-03 19:08

import archytee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=90)),
                ('clientDesignation', models.CharField(max_length=80)),
                ('feedback', models.TextField(max_length=500)),
                ('rating', models.IntegerField(max_length=1)),
                ('slide', models.IntegerField(max_length=1)),
                ('image', models.ImageField(upload_to='archytee/static/archytee/images/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='commercialProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.IntegerField()),
                ('image1', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image2', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image3', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image4', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='designProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.IntegerField()),
                ('image1', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image2', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image3', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image4', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='interiorProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.IntegerField()),
                ('image1', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image2', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image3', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image4', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='RecentProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('box', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='archytee/static/archytee/images/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='residentialProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.IntegerField()),
                ('image1', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image2', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image3', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
                ('image4', models.ImageField(upload_to=archytee.models.get_image_upload_path)),
            ],
        ),
    ]
