# Generated by Django 4.2.7 on 2023-11-06 12:23

import archytee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archytee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialprojects',
            name='page',
            field=models.CharField(default='commercial', max_length=100),
        ),
        migrations.AddField(
            model_name='commercialprojects',
            name='slide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designprojects',
            name='page',
            field=models.CharField(default='design', max_length=100),
        ),
        migrations.AddField(
            model_name='designprojects',
            name='slide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiorprojects',
            name='page',
            field=models.CharField(default='interior', max_length=100),
        ),
        migrations.AddField(
            model_name='interiorprojects',
            name='slide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='LongText',
            field=models.TextField(default='testing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialprojects',
            name='page',
            field=models.CharField(default='residential', max_length=100),
        ),
        migrations.AddField(
            model_name='residentialprojects',
            name='slide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialprojects',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='commercialprojects',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='commercialprojects',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='commercialprojects',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='designprojects',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='designprojects',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='designprojects',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='designprojects',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='interiorprojects',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='interiorprojects',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='interiorprojects',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='interiorprojects',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='properties',
            name='text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='residentialprojects',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='residentialprojects',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='residentialprojects',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='residentialprojects',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=archytee.models.get_image_upload_path),
        ),
    ]
