# Generated by Django 4.2.7 on 2023-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archytee', '0002_commercialprojects_page_commercialprojects_slide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='page',
            field=models.CharField(default='properties', max_length=100),
        ),
    ]
