# Generated by Django 4.2.7 on 2023-11-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archytee', '0003_properties_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='slide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
